### ISSUE TITLE
Замедление перехода из зоны приключения на остров

### ISSUE THREAD

**Issue by Urvdmih** [fedorovvl/tso_client#11]
Заметил особенность, что со временем, когда выходишь из приклов, начинает тормозить переход, долго висит загрузка.
Особенно заметно если часто делаешь однотипные быстрые сценарии типа горного братства. Решается только перезапуском клиента.
Это возможно пофиксить?

**Comment by fedorovvl** [comment]
друг, я не разработчик игры :)
нет шансов что я найду какую нибудь утечку памяти из-за частых загрузок игровых зон
