### ISSUE TITLE
Geo's template folder always resets to default

### ISSUE THREAD

**Issue by borsti67** [fedorovvl/tso_client#154]
Hi,
after upgrading to v22.11.2022 each time I want to load a template the dialogue starts in "my documents" instead of the folder which was used before. The other tools seemingly don't have this issue.
BTW: Having a default template as a one-click-load would be nice. ;)

**Comment by Kshyhoo67** [comment]
In this version there is a function in the options to set the default path.

**Comment by borsti67** [comment]
Thanks - for all those who are blind like me, that's in the Options below the leftmost menu, not in that below "Tools" 🤣
