### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by pressgamer** [fedorovvl/tso_client#155]
### Discussed in https://github.com/fedorovvl/tso_client/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **Anprivate** September 22, 2022</sup>
> support for user scripts (place user.js to tso_portable folder)

О, мечты сбываются, я как раз хотел просить либо какие-нибудь скрипты, либо некий API
А есть какая-нибудь документация?</div>

**Comment by pressgamer** [comment]
Hi guys. Is possible to make script for adventures?
I mind make auto battles with generals on adventure.

**Comment by fedorovvl** [comment]
1. issue not for asking features
2. no auto battles/trades/etc
