### ISSUE TITLE
don't touch %temp%/tso_portable if --skip is specified

### ISSUE THREAD

**Issue by h31p** [fedorovvl/tso_client#156]
greetings, and thanks for that great piece of software!

seems like client.exe always re-nunpacking %temp%/tso_portable contents from itself during startup, which is slightly inconvenient in the case when some local modifications over that folder are used. can you please change that behavior in further releases, so client.exe would not touch that folder at all (except settings and/or temporary files), if --skip key is used? thank you!

**Comment by fedorovvl** [comment]
re-nunpacking disables with --debug flag

**Comment by h31p** [comment]
thanks for clarification, i'll use it as workaround.
but, i guess, it will be more intuitive if --skip would stop re-unpacking too. that was the first thing i've tried: if we don't want to update content - we expect everything to be left as is, right? moreover, i suspect with --debug it will do extra [unneeded] work, which is not exactly what we need to just keep things unchanged.
whatever it is, that was just my 5 cents, you decide. thank you!

**Comment by fedorovvl** [comment]
--skip should not be used.. this flag only for critical situations
--debug used when needs local changes for debugging
why you using --skip? maybe u doing smth wrong?

**Comment by h31p** [comment]
no-no, from the point of ordinary usage - everything working as expected, but that's not my case :)
as i've described, i need some local changes in tso_portable contents to stay intact between client relaunches, and with --skip it was just a try to get the desired behavior. unfortunately, for now - unsuccessful try, despite of habitual logic :)
p.s.: the client still warns me if new version is available - so it's ok, i'm just updating it manually when needed.
