### ISSUE TITLE
mission impossible

### ISSUE THREAD

**Issue by luchoplay** [fedorovvl/tso_client#165]
I have a great idea if it can be achieved and that is that in the generals are automatically loaded with the troops already selected to take to the adventures.

What is this?  Force use GC

**Comment by MikeIceman** [comment]
It forces to use garbage collector to reduce memory consumption.

About generals autofill: this is not so easy case to implement in the nearest future. You can try it by yourself if you want.

**Comment by krajanos** [comment]
Loading generals with army can be done. But to present some useful tool is more time needed.

**Comment by fedorovvl** [comment]
try latest test build https://nightly.link/fedorovvl/tso_client/workflows/msbuild/master/client.zip

**Comment by fedorovvl** [comment]
implemented in 1.5.5
