### ISSUE TITLE
Update 2023-2-7 seems to have broken the client

### ISSUE THREAD

**Issue by Sophist-UK** [fedorovvl/tso_client#173]
Will there be an update?

**Comment by fedorovvl** [comment]
https://github.com/fedorovvl/tso_client/wiki/Maintenance-and-upstream-SWF

**Comment by Sophist-UK** [comment]
We unchecked the tick box and were able to sign in.

**Comment by Sophist-UK** [comment]
And thank you @fedorovvl for such a fast response.
