### ISSUE TITLE
ssl error on windows <10

### ISSUE THREAD

**Issue by h31p** [fedorovvl/tso_client#180]
ssl cipher suite was changed on settlers servers recently, making it impossible to use tso_client with windows versions older than 10.
any chances for making it working again (without upgrading to win10/11) in future releases, or windows upgrade is the only way?

**Comment by fedorovvl** [comment]
windows 7 and perhaps 8 does not have tls cipher that used on tso site
```
PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|     compressors:
|       NULL
|     cipher preference: server
|_  least strength: A
```
im trying to write new auth methods with custom tls provider

**Comment by fedorovvl** [comment]
pls check latest release

**Comment by h31p** [comment]
great job, it's working again! thanks for the another inventive salvation :)
