### ISSUE TITLE
trojan again

### ISSUE THREAD

**Issue by WaZZo2010** [fedorovvl/tso_client#188]
![trojan](https://user-images.githubusercontent.com/114599482/221925070-ac339f57-071d-49f5-955e-32f0e6d0c836.png)

win32/trojan.generic.hglas9ga

**Comment by fedorovvl** [comment]
report false positive..
check file on virustotal

**Comment by fedorovvl** [comment]
i've added github action for auto build binary..
you can download artifacr from latest build and check https://github.com/fedorovvl/tso_client/actions

**Comment by fedorovvl** [comment]
false positive
