### ISSUE TITLE
Suggestion: save location and default template

### ISSUE THREAD

**Issue by skelgaard** [fedorovvl/tso_client#20]
it would be nice, if a default save location could be given like same place as the exe file and if a default template could be setup, so that it will load that from start when going into explores f3 view

**Comment by BasilMas** [comment]
If I understood Sirris' explanation correctly, the client does not know where it was launched from. I guess My documents is not the most appropriate place to keep templates, but as a temporary solution I used a shortcut to the right folder in 'MyDocuments'.
