### ISSUE TITLE
[army] send option missiong / impossible to send when everything is already in place

### ISSUE THREAD

**Issue by borsti67** [fedorovvl/tso_client#248]
After loading an army template there comes a new window displaying the status. There you usually press "load troops" (I'm playing in German so the actual name may be something else). Then the generals will be supplied and you get back to the initial screen where all necessary generals are checked and you can send them to the adventure.

In case you load a template where nothing needs to be changed there is no "load troops" button but also no "continue" or "send". You only can "close" which _completely_ closes the army window instead of just going one step back.

But moreover, if you now reopen the army tool, you will see that no generals are selected for sending any more, so you need to remember which ones and check them manually.

As a workaround you can also just unload one general and restart the process from loading the template, but I consider that quite dull ;-)

So I would appreciate if after loading nothing needs to be changed, either display "load troops" anyway or display e.g. "continue" instead to have the generals ticked and proceed back to the initial screen where we can send them. Or, may be even easier, have the "send to adventure"-button also on this screen to avoid the step of going back at all.

(Client v1.5.6.1)

**Comment by fedorovvl** [comment]
click reset and then send

**Comment by borsti67** [comment]
Oh, so I misinterpreted what "reset" would do? I'll give it a try, thanks!
