### ISSUE TITLE
collectibes not all marked on friend island

### ISSUE THREAD

**Issue by wofo99** [fedorovvl/tso_client#249]
Dears, since 2 or 3 releases I notice a rather minor issue: when I hop to another guildmembers island with active collectibles and run CTRL-F4 to mark them, it will always skip one last item and I can see it having no flag. I then hop back to home-island, go there again and run CTRL-F4 once more: I can hear the bell ring and the last collectible is marked as well then.
BTW: I use UbiCollect 2.2

Maybe someone can find the time to look into this. As said, its no blocking issue, just not neat :-)

Many thanks to all of you for this incredible work and best regards :-)

**Comment by fedorovvl** [comment]
ubicollect replaced by client itself
