### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by tehervonat** [fedorovvl/tso_client#253]
The client says "E-mail or password not correct" when i try to login. One hour earlier there was not any problem . I checked the email and password and both are correct. I login on website also with success. What is the problem?

Thank you in advance!

**Comment by fedorovvl** [comment]
try to turn off 2-way auth

**Comment by skelgaard** [comment]
account.ubisoft.com

**Comment by SirAdams** [comment]
Yes, after disable 2-step auth client can login. But this is not a solution to the problem.

**Comment by fedorovvl** [comment]
> untill and if possible for sirris to make 2 fact work, it is the only sollution there is a workaround with fastlogin but it can be dangerous
why it can be dangerous?

**Comment by C-o-l-u-m-b-o** [comment]
yes, please fix this 2-step auth...switching off the 2-setp auth is not good.

**Comment by C-o-l-u-m-b-o** [comment]
> untill and if possible for sirris to make 2 fact work, it is the only sollution there is a workaround with fastlogin but it can be dangerous

can you describe the workaround? As far as I understand, you need first a successful (normal) login until you can use "fastlogin"? Am I wrong? Thanks

**Comment by deeseem** [comment]
Neither "--fastlogin" or "/fastlogin" appear to be accepted paramaters in the target box. Please advise.

**Comment by deeseem** [comment]
Oh. You have to create a space between ".exe" and "/fastlogin" e.g.: .exe /fastlogin
