### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by Ingonduran** [fedorovvl/tso_client#254]
When I try to enter through the client, it login fine, but then it sends the error that I attached in the screenshot.
![2023-04-13 13_49_39-The Settlers Online](https://user-images.githubusercontent.com/4731857/231843604-238b0ffa-dfd7-4938-8d45-56ed9f9fc086.png)

This happend all day, and not only to me.

**Comment by skelgaard** [comment]
if you are using fastlogin, this is the error if your cookie is not working anymore and new cookie is needed, so login normal, then fastlogin can be used again.

**Comment by skelgaard** [comment]
2factor doesn't work with the client. you need to turn it of on account.ubisoft.com, then after login, you can use fastlogin and 2factor again, but if you login on browser or other computer this has to be repeated.

**Comment by Mazimus332** [comment]
Ingonduran, desactiva el factor de doble autenticación desde https://account.ubisoft.com/es-ES y te dejará de aparecer el mensaje de "e-mail o contreseña errada"
Si alguien te dijo que uses --fastlogin y no lo leíste del servidor de Discord, te informó mal, lee el funcionamiento del --fastlogin y por qué te está fallando.

* `cliente.exe --fastlogin` - **No recomendado a menos que comprendas los posibles problemas. Lee atentamente este párrafo.**. El parámetro te permite omitir todos los pasos de autorización de Ubisoft y ejecutar el cliente al instante. La primera ejecución del cliente debe realizarse sin este parámetro, pirmero debe escribirse el token de autorización en el archivo settings.dat y luego se puede añadir --fastlogin para la autenticación posterior. Cualquier inicio de sesión desde otro lugar (desde otra computadora, desde el navegador hasta la página principal de Settlers, etc.) hará que este token se invalide y obtendrá un error (el tipo dando martillazos al ordenador) en el próximo inicio del cliente.

> **Caso en el que se recomienda**: Solamente abres el juego desde el client.exe, no abres la página inicial del juego, no abres el foro.

> Además, settings.dat guardará información sobre tu idioma, ventana, ubicollect, clientconfig, etc., si se especificaron durante la primera ejecución. Esto significa que si en tu primera ejecución haces uso de "client.exe --lang es --window maximized --collect", la segunda ejecución "client.exe --fastlogin" comenzará con el idioma ruso, la ventana maximizada y UbiCollect habilitado.

**Comment by Ingonduran** [comment]
Gracias! Solucionado!
