### ISSUE TITLE
New login problema

### ISSUE THREAD

**Issue by Ingonduran** [fedorovvl/tso_client#255]
Now the client don't allow to load game
![2023-04-13 17_51_06-The Settlers Online](https://user-images.githubusercontent.com/4731857/231890939-80054739-b83f-470a-b1fa-e597f742d5fc.png)

**Comment by Mazimus332** [comment]
Este problema no parece estar relacionado con el Cliente Flash
Lee el post: https://forum.thesettlersonline.es/threads/21730-Problemas-de-acceso-con-Unity-y-cliente

**Comment by Ingonduran** [comment]
Cierto, el problema persiste vía web
