### ISSUE TITLE
Can no longer log on

### ISSUE THREAD

**Issue by Zig3tPuce** [fedorovvl/tso_client#256]
Hi,
I can no longer log on to the game. I logged off about an hour ago, and when tried to log back on about 30 minutes ago, I could see some downloading was happening, after which I got a message going ; "File loading failed. Please check your network connection, clean your browser cache of try again later."
Access to the game over the web site is ok and my network connection too.

**Comment by Maetel2002** [comment]
Hi,
I have the same issue, trying to connect me on the French TSO server. But all fine (... for the moment), with the European English server.

**Comment by Tartapuce** [comment]
Hi,
Same issue in logging process too !!! on french server.
After an update this morning, file settings.dat has been modified.... and isn't working anyway....

**Comment by fedorovvl** [comment]
fixed
sry for that.. my mistake

**Comment by Zig3tPuce** [comment]
Thanks for the update Sirris, indeed, it's working much better now :)

**Comment by Tartapuce** [comment]
Yeah, it works again...
Thanks a lot !!!!!
