### ISSUE TITLE
help  vladimir (aka SirriS)

### ISSUE THREAD

**Issue by luchoplay** [fedorovvl/tso_client#259]
Hola saludos desde Uruguay tengo un par de ideas y porque surgen algunos problemas 
1) Después de cada evento tengo que agregar a los nuevos exploradores al .txt, pero en el archivo de texto no aparecen los nombres de los exploradores, solo unos números y si quiero cambiar la búsqueda tengo que esperar a que terminen todos los exploradores y cambiar porque no se encuentran los nombres un ejemplo: nombre "91000_0":      búsqueda "2,3" esto si sé que es, pero lo que molesta es no saber el nombre de cada explorador 

2) este cliente se ve que utiliza mucho más gráficos y se nota como más lento y todo el gremio piensa que es eso y estamos esperando a la próxima actualización 

3) el cliente 1.5.6.1 estaba mejor, pero con el cambio de cliente algunas plantillas dan error y hay que hacerlas de nuevo con el nuevo cliente 1.5.6.2

4) la ventana ejército de carga al ser eliminada se extraña no poder usarla como que cuesta más acostumbrarse y solo uso la función de ataque para cargar tropas, mover y atacar solo con esa función 

5) simplemente dar las gracias por el esfuerzo que haces para que todos podamos jugar, espero que pronto saques una nueva actualización

**Comment by Mazimus332** [comment]
Hola Lucho,
Soy del servidor Español, espero resolverte algunas dudas.
1. Esa sugerencia es buena, pero es posible que rompa las anteriores plantillas de exploradores, las haga inutilizables, a ver qué dice SirriS.

2. En cuanto al rendimiento del juego, has de pensar que el único actualizador del cliente es SirriS, ha intentado optimizar el cliente con la opción "Forzar el uso de Garbage Collector" pero no parece una tarea fácil mejorar el rendimiento de manera significativa.

3. Las plantillas creadas en la versión 1.5.6.1 de ejército y guerra mundana son en principio "compatibles" con 1.5.6.2 en el sentido de que se pueden aplicar para luego volver a guardar con el nuevo formato. Las plantillas con un formato anterior si es posible que directamente no funcionen y se tengan que hacer de 0, aunque no sé exactamente a partir de qué versión dejan de ser "compatibles", ya que yo en mi caso las fui actualizando gradualmente y no tuve problema con ninguna.

4. Creo que fusionar las ventanas ha simplificado mucho el entendimiento para la gente recién introducida, reduce la cantidad de clics y es más intuitivo, en un mes ya estarás acostumbrado...

Por cierto, si no estás ya dentro, te invito a unirte al Discord que creé la comunidad Hispana, donde puedes discutir cualquier cosa relacionada con el cliente o el juego, compartir plantillas de aventuras, potenciadores, etc. ;)
https://discord.gg/Gkt2DYtUyn

Y por si no la viste, revisa la wiki del cliente, que fui escribiendo yo, este link en concreto va a la Guerra Mundana https://github.com/fedorovvl/tso_client/wiki/Informaci%C3%B3n-general#guerra-mundana-f10

**Comment by Cdrwbw** [comment]
"Hola saludos desde Uruguay tengo un par de ideas y porque surgen algunos problemas

Después de cada evento tengo que agregar a los nuevos exploradores al .txt, pero en el archivo de texto no aparecen los nombres de los exploradores, solo unos números y si quiero cambiar la búsqueda tengo que esperar a que terminen todos los exploradores y cambiar porque no se encuentran los nombres un ejemplo: nombre "91000_0": búsqueda "2,3" esto si sé que es, pero lo que molesta es no saber el nombre de cada explorador"

==> Hola Lucho,
 cuando hay nuevos exploradores o geólogos, me quedo con los nuevos en especialistas, los demás se han ido, asigno su tarea a los nuevos y guardo el modelo.
 Luego abro el modelo de todos los exploradores, abro el modelo de los nuevos explosivos y los copio en el primer modelo (cuidado con la coma), guardo. 
El tiempo según mi modelo general contiene todos los exploradores

Traducido por deepl

**Comment by fedorovvl** [comment]
i don't understand so closed
