### ISSUE TITLE
Translate (English)

### ISSUE THREAD

**Issue by azurpc** [fedorovvl/tso_client#26]
Hi, I've made a translation...
![login english](https://user-images.githubusercontent.com/109301910/183242580-3637e854-aedc-4793-8700-a52a46bf748e.png)
![back english](https://user-images.githubusercontent.com/109301910/183242588-02730fd9-064d-409d-8ab2-43ee4db31e4c.png)

**Comment by fedorovvl** [comment]
cool.. now you can build your own client with this textures.. just replace back.png and login.png and compile
