### ISSUE TITLE
Logging issue 

### ISSUE THREAD

**Issue by Tartapuce** [fedorovvl/tso_client#262]
Hello, 
As it happened a few days ago, I get this message again when I try to log into the game......
I think the client.swf file is corrupt.....
![Bug](https://user-images.githubusercontent.com/118884539/236453208-d8e6ff47-d459-4534-9c00-1ad41300e6f2.jpg)

If it is possible to correct it ! 
The game is working in my browsers....
Thanks...

**Comment by fedorovvl** [comment]
try now

**Comment by Tartapuce** [comment]
Ok, it download's a new file, and it seems to work again.
Thanks, you're great !
Thanks...
