### ISSUE TITLE
script help Vladimir

### ISSUE THREAD

**Issue by luchoplay** [fedorovvl/tso_client#267]
Hola puedes hacer un script para grabacion de minas de cobre hierro oro y las otras que haga mas facil subirlas de level con un solo clic 

otro script para comercio que podamos grabar las ofertas en comercio 

estaria muy bueno saber si lees los mensajes o respondes aqui y en donde publicas el cliente del juego nunca me respondes 

el mensaje prefieres en ingles o ruso?

hello can you make a script for recording copper iron gold mines and the others to make it easier to upload them from level with one click 

another script for trading that we can record the offers in trading 

it would be very nice to know if you read the messages or reply here and where you post the game client you never reply to me 

do you prefer the message in english or russian?

здравствуйте, можете ли вы сделать скрипт для записи медных железных золотых шахт и других, который облегчает их загрузку с уровня одним кликом. 

другой скрипт для торговли, чтобы мы могли записывать предложения в торговле. 

было бы очень приятно узнать, читаете ли вы сообщения или отвечаете здесь и где вы размещаете игровой клиент вы никогда не отвечаете мне 

предпочитаете ли вы сообщения на английском или русском?

**Comment by fedorovvl** [comment]
hi. if u mean feedback window then its oneway communication =) i cant reply to feedback messages
about autobuild and autotrade.. short answer - no
any auto* features are prohibited in my client

**Comment by luchoplay** [comment]
> Hola. si te refieres a la ventana de comentarios, entonces es una comunicación unidireccional =) no puedo responder a los mensajes de comentarios sobre la compilación automática y el comercio automático ... respuesta corta: no hay funciones automáticas * prohibidas en mi cliente

y se puede buscar la manera de que las minas de cobre y otras se puedan grabar y subir a level 5  y perdon con tantas preguntas y siempre estoy esperando con ansias la actualizacion de cosas nuevas 1 cosa mas el filtro de una vez por todas que esta en opciones para que sirve

**Comment by luchoplay** [comment]
cuando llegan los generales en la aventura los mandamos a estrella pero se puede hacer que de estrella se coloquen en la pocicion deseada en la aventura??? eso se puede hacer ??? @fedorovvl

**Comment by luchoplay** [comment]
> cuando llegan los generales en la aventura los mandamos a estrella pero se puede hacer que de estrella se coloquen en la pocicion deseada en la aventura??? eso se puede hacer???@fedorovvl ??? esto es posible

**Comment by fedorovvl** [comment]
from star u can land generals only on allowed landing zones
closed, not issue
