### ISSUE TITLE
collectibles color (and shape if possible)

### ISSUE THREAD

**Issue by h31p** [fedorovvl/tso_client#277]
```[feature] collections highlight. ubicollect support removed (main settings)```

that's quite cool, thank you for the riddance of additional tools for playing!

but can we ask you to make this integrated highlight to be slightly more configurable?

with previous versions, i've used to select "white on white" color scheme settings - this greatly improving collectibles visibility when the island is very densely built up (on high levels).

even more, in ancient times of browser+js version of this hl, it was possible to just replace pic - so i've used to use (sry for tautology) a white _**square**_ instead of circle, thus making a good chance to see at least a corner of collectible even when it's completely overlapped by building or rock, that takes place **very** often, again, when the island is completely filled up.

so, the ability to choose colors would be nice, while ability to choose custom shape or pic would be just perfect ) thanks again

**Comment by Catavasiya** [comment]
![image](https://github.com/fedorovvl/tso_client/assets/128522616/1645877c-d029-4257-bd58-7daa596cb8c2)

**Comment by h31p** [comment]
aarrghh, i've just missed that:

![CKDMk1](https://github.com/fedorovvl/tso_client/assets/40469877/07a1a2ec-ba9c-4081-80bd-500463e39320)

sorry for false alert, about colors )
and what about shape?

**Comment by h31p** [comment]
nevermind. false alert, sorry )
