### ISSUE TITLE
I cannot log in

### ISSUE THREAD

**Issue by komarzycho** [fedorovvl/tso_client#280]
Whenever I'm trying to log in it says "email or password not correct" and to precise it went like this:
Login attempt #0
Authentication ubi
Successful authenication
Authenication uplay
email or password not corrent.

I know it's correct 100% cuz i've been using it to log in via website or ubisoft client, but what I've noticed is every time im trying to log in through launcher, there is new mail on my gmail with security code from ubisoft so i think ubisoft might blocking me from logging into the client from security reasons cuz it sees the launcher as something unknown. It's just my thoughs but maybe someone who's reading it might help me to understand the problem and fix it cuz I'd rather use your launcher than log in every time though website.

**Comment by skelgaard** [comment]
do you have 2factor enabled ? 
the client can't support that, so if that is enabled, it can't login

**Comment by komarzycho** [comment]
tbh i have no idea what 2factor is

**Comment by BasilMas** [comment]
> tbh i have no idea what 2factor is

go to https://account.ubisoft.com/en
login > security > turn 2 factor off
![image](https://github.com/fedorovvl/tso_client/assets/76757249/7ce9064e-b597-451b-afc2-d7038ac901c5)

**Comment by komarzycho** [comment]
thank you so much <3

**Comment by BasilMas** [comment]
Done?

**Comment by komarzycho** [comment]
I don’t know yet,im away,I’ll be back home at Monday,than i’ll let u know,thanks for keeping interest

**Comment by komarzycho** [comment]
IT WORKED,THANK YOU <333
