### ISSUE TITLE
Imposible to run client

### ISSUE THREAD

**Issue by Ingonduran** [fedorovvl/tso_client#285]
Hio! Until today, everything had worked perfectly, now the client crashes without any warning, I haven't updated anything on the PC.

This is the log:
Last exception time: 25-06-2023 18:09:09
Message: Se produjo una excepción en el destino de la invocación.
Source: mscorlib
Target: System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
Message: Falta el elemento raíz.
Source: System.Xml
Target: Void Throw(System.Exception)

**Comment by fedorovvl** [comment]
delete settings.dat file and try again

**Comment by Ingonduran** [comment]
Same problem, the error change a little

Last exception time: 26-06-2023 12:23:10
Message: Falta el elemento raíz.
Source: System.Xml
Target: Void Throw(System.Exception)

**Comment by fedorovvl** [comment]
idk.. try to delete tso_portable folder (backup settings.json first)

**Comment by Ingonduran** [comment]
The folder where i put the client? I don't have any "settings.json" file in there

**Comment by fedorovvl** [comment]
![изображение](https://github.com/fedorovvl/tso_client/assets/31754742/27b7bb1b-faa3-4c09-b303-52a087dddd45)
click on box and delete everything except settings.json (if exists)

**Comment by Ingonduran** [comment]
Thanks! resoveld problem!
