### ISSUE TITLE
Can't grab cookies?

### ISSUE THREAD

**Issue by wizofaus** [fedorovvl/tso_client#287]
Had this for the first time today:

Login attempt #0
Authentication ubi
Successful authentication 
Authentication uplay
Successful authentication 
Request play page
Can't grab cookies :'(

Tried 4 times, even after clearing tso_portable folder, same result.

I'm assuming it's due to a scheduled maintenance period.  Will there be an updated client (and in general, how often should we expect to need to update it?)

**Comment by fedorovvl** [comment]
wait till maintenance done
