### ISSUE TITLE
Today, Mundane Warfare has made 600 of my mounted marksmen disappear

### ISSUE THREAD

**Issue by Zig3tPuce** [fedorovvl/tso_client#290]
I have just found out that this happened because I have modified my file manually and loaded one of my General Majors with 200 troops more than it could take.
So, every time that I tried to load that general with troops, 200 mounted marksmen would simply disappear.

**Comment by fedorovvl** [comment]
keep manually modify templates and u get not only disappeared troops..

**Comment by Zig3tPuce** [comment]
No ? what else do I get, I'm curious ^^
