### ISSUE TITLE
i need answers please vladimir

### ISSUE THREAD

**Issue by luchoplay** [fedorovvl/tso_client#292]
1) [build level (you can explain better so I can to guild mates)

2) [core] new timed queue logic ( you can explain better so I can to guild mates )

3) [specification] default task by specification type (specification window - configuration icon) (you can explain better so I can to guild mates)

4) [information about depleted mines (can you explain better so I can to guild mates)

please answer 
1)
2)
3)
4)
I use translator to communicate with you my language is Spanish, I hope you understand me.
Translated with www.DeepL.com/Translator (free version)

**Comment by fedorovvl** [comment]
0) its not issue
1) building level in buff window
2) new logic for timed queue...
3) default task by specialist type
4) info ab depleted mines in specialists window
