### ISSUE TITLE
"Client outdated" message

### ISSUE THREAD

**Issue by SasSam** [fedorovvl/tso_client#293]
Hi,

I started the client this morning, and I saw that it downloaded something .. then when I tried to log in and play, the game was loaded, but before my island could turn up, a modal window came up and said: "Client outdated - Please delete your browser cache and try to log in again."

![image](https://github.com/fedorovvl/tso_client/assets/496429/4ca7c59e-3757-477b-9014-130cab9493b1)

I deleted the `tso_portable` folder, but it doesn't help. So I can't play the game with the client now. 

The client is the latest (1.5.6.3).

Please advise something. What do I do wrong? Thanks in advance!

**Comment by fedorovvl** [comment]
hi. should already be fixed. try to play

**Comment by SasSam** [comment]
> hi. should already be fixed. try to play

Nope.. still the same. 😢

**Comment by fedorovvl** [comment]
try now =)

**Comment by SasSam** [comment]
> try now =)

👍  it's working again, thank you! 🎉

**Comment by blackmedusa54** [comment]
I have the same issue, client outdated , and dont know what to do, the -skip dont work here
