### ISSUE TITLE
client outdated

### ISSUE THREAD

**Issue by blackmedusa54** [fedorovvl/tso_client#294]
i get the client outdated, deleted the tso portable folder, tried to putt the -skip, nothing works

**Comment by fedorovvl** [comment]
on which realm u play?

**Comment by blackmedusa54** [comment]
dutch server

**Comment by fedorovvl** [comment]
try again in 5 min

**Comment by blackmedusa54** [comment]
ok will do

**Comment by blackmedusa54** [comment]
it works now, thank you very much, does this mean that  other people can login again on the dutch server too?

**Comment by fedorovvl** [comment]
> it works now, thank you very much, does this mean that other people can login again on the dutch server too?

yep

**Comment by blackmedusa54** [comment]
cool i will tell them,  thank you again  👯‍♀️
