### ISSUE TITLE
Building buff issue with the "storage full" state

### ISSUE THREAD

**Issue by SasSam** [fedorovvl/tso_client#295]
Hi,

The building buff works nicely in general, however, I noticed an issue... If the building has a bouncing barrels icon (storage full), it should not allow buffing the building in the template list. Currently, it says "ready", and the building will be buffed.

Is it something that you could fix?

**Comment by fedorovvl** [comment]
what purpose to buff building that cant produce items?

**Comment by fedorovvl** [comment]
change "Buff buildings" to "Only active" instead "all" wont help?

**Comment by SasSam** [comment]
Nope.. I tried both settings. It says "ready" all the time in the list.

**Comment by fedorovvl** [comment]
implemented in https://github.com/fedorovvl/tso_client/commit/689f65ab785c5850ce4d78d2785cce6401bb17a8
pls check on latest test build (not release)

**Comment by fedorovvl** [comment]
released in 1.5.6.4
