### ISSUE TITLE
Client Outdated / Ares

### ISSUE THREAD

**Issue by rsutherlandii** [fedorovvl/tso_client#296]
I upgraded manually yesterday, started getting this message. is there a way to fix it?

**Comment by rsutherlandii** [comment]
this is still a problem. not in chronological order, i tried: uninstalling the client, reinstalling the client and replacing all current files; reinstalling 07/27/2023 client files multiple times; reinstalling 07/14/2023 client multiple times; upgraded to latest tampermonkey script;

**Comment by fedorovvl** [comment]
u need client_upstream.swf if u use tampermonkey
download it and rename to client.swf

**Comment by rsutherlandii** [comment]
Sorry to be obtuse, but I don't see that in the wiki/download file, nor in the codebase. where do i download it?

**Comment by rsutherlandii** [comment]
nevermind. I found it. :)

**Comment by rsutherlandii** [comment]
didnt work...any more ideas?

**Comment by fedorovvl** [comment]
can u try portable client version?

**Comment by rsutherlandii** [comment]
I'm unclear the difference. but I'll review the wiki and get back to you.

**Comment by rsutherlandii** [comment]
Implemented the portable client; i'm online. thank you for your hard work!!

**Comment by rsutherlandii** [comment]
closed
