### ISSUE TITLE
Buffs on adventures

### ISSUE THREAD

**Issue by dopiotrko** [fedorovvl/tso_client#305]
Can buffs work on adventures?
Well ... I know they can. 
I modified my local "6-buffs.js" and it works.
Can I commit this here?

**Comment by fedorovvl** [comment]
sure u can make a PR.. i'll check

**Comment by fedorovvl** [comment]
implemented in https://github.com/fedorovvl/tso_client/commit/7c963fd3b55f8445dc1e0dc0a7fda09c41fdb87e
