### ISSUE TITLE
Impossible to connect on game....

### ISSUE THREAD

**Issue by Tartapuce** [fedorovvl/tso_client#309]
Hello,
Since yesterday night, it is impossible to connect on TSO (in france).
The game loads correctly but never allow to play. 
![1](https://github.com/fedorovvl/tso_client/assets/118884539/aa6bacfa-2875-4884-bd60-e8180d81b5dd)
It stops and after a few minutes, it says that connection with server is broken.
Here is a screen capture...
![2](https://github.com/fedorovvl/tso_client/assets/118884539/4f1828b3-0167-4afd-bbc2-489d5531528d)

The Unity version works but is bugged (new bugs on explorators)

Is it possible to do something ?
Thanks

**Comment by zebecasse** [comment]
In the last error.log i have that :

Message: An exception was thrown by the target of a call.
Source: mscorlib
Target: System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
Message: Unable to set Visibility or call Show, ShowDialog, or WindowInteropHelper.EnsureHandle after closing a Window object.
Source: PresentationFramework
Target: Void VerifyCanShow()

**Comment by Tartapuce** [comment]
Hello,
I cant confirm this, i've the same message in error.log

**Comment by BasilMas** [comment]
try the latest build

**Comment by zebecasse** [comment]
Sorry, but the last build of what ?

**Comment by annutwork** [comment]
Since yesterday afternoon when the client autodownloaded a new update I can't get in, have the same issue as reported above.
I log into Sandycove, European English, from NL.  Someone else in the house can log in to the same server with their account on a different machine using the current version of the client.

**Comment by Or0r** [comment]
> Bonjour, Depuis hier soir, il est impossible de se connecter sur TSO (en france). Le jeu se charge correctement mais ne permet jamais de jouer. Il s'arrête et après quelques minutes, il indique que la connexion avec le serveur est interrompue. Voici une capture d'écran... ![1](https://user-images.githubusercontent.com/118884539/269874870-aa6bacfa-2875-4884-bd60-e8180d81b5dd.jpg) ![2](https://user-images.githubusercontent.com/118884539/269874927-4f1828b3-0167-4afd-bbc2-489d5531528d.jpg)
> 
> La version Unity fonctionne mais est buggée (nouveaux bugs sur les explorateurs)
> 
> Est-il possible de faire quelque chose ? Merci

J'ai moi aussi la meme erreur > serveur France Ambre, ce matin ça a téléchargé automatiquement, j'ai eu l'espoir que ça allait marcher, mais j'ai toujours la meme erreur :(

**Comment by Tartapuce** [comment]
For zebecasse => Tle last build of client.exe link : https://nightly.link/fedorovvl/tso_client/workflows/msbuild/master/client.zip
Sinon, il est là (dans le rectangle rouge)
![Lien](https://github.com/fedorovvl/tso_client/assets/118884539/999ffe05-ec61-4f04-a30c-59c4a5a003a2)
Bon usage....

**Comment by zebecasse** [comment]
merci infiniment, ca fonctionne !
Many thank, issu esolve

**Comment by Cdrwbw** [comment]
partially resolved no chat, green dots but private messages ok

**Comment by BasilMas** [comment]
> Sorry, but the last build of what ?

of client

![image](https://github.com/fedorovvl/tso_client/assets/76757249/9faa5363-6aee-46c5-97f0-fa1a95feb21d)

**Comment by BasilMas** [comment]
> partially resolved no chat, green dots but private messages ok

no chats now, till to update for all realms

**Comment by Or0r** [comment]
oui partiellement résolu, je disais ok pour la connexion ^^
pas de points verts , pas de tchats, les généraux ne s'affichent pas dans le cadre 

![image](https://github.com/fedorovvl/tso_client/assets/146007252/aa8cb31c-97f1-4d07-8983-461f40787bbb)

**Comment by Tartapuce** [comment]
Or0r, je pense que ton installation à un problème. Essaies de vider ton cache en l'effaçant au lancement. Pour cette fenêtre, le titre chez moi est "Guerre futile", les généraux sont présents, pas de case options......
![guerre futile](https://github.com/fedorovvl/tso_client/assets/118884539/a71d547d-5ce5-46c7-b672-a9a6bc4751dd)
En revanche, oui, le chat est HS..... et les autres joueurs (amis et guildeux) n'ont pas de point vert. 
Ce client est une nighty build. Donc, soit créer une issue (mais à partir d'une version nighty, c'est bizarre), ou essayer de retélécharger la build suivante.....
L'essentiel est de pouvoir jouer....
Ah, à propos, il vaut mieux utiliser l'anglais pour obtenir des réponses plus rapides....

**Comment by Pervect69** [comment]
Same issue since September 26. Version 1.5.6.3 on Windows 10
![Launch Print Screen](https://github.com/fedorovvl/tso_client/assets/146184286/014f9529-aa20-48c5-9855-fd8bcb4e4a76)
![Connection Print Screen](https://github.com/fedorovvl/tso_client/assets/146184286/2dae55cb-4dc0-4195-99c3-c06069af4cf8)

![Server Lost Print Screen](https://github.com/fedorovvl/tso_client/assets/146184286/5aa69b11-97b7-46f4-b7ae-93e644a82495)

**Comment by Pervect69** [comment]
Installing newest build resolved the issue. Thanks, BasilMas.

**Comment by sroca-81** [comment]
![image](https://github.com/fedorovvl/tso_client/assets/106090001/5c62c517-f0c4-48ff-818e-46587b05df3a)
Installing latest build have chat issue (server IT)

**Comment by BasilMas** [comment]
no chats now for realms after infrastructure maintenance, no online marks
be patient and wait to fix it!

**Comment by fedorovvl** [comment]
fixed i suppose =))

**Comment by Tartapuce** [comment]
Yes, of course, and many other things too !!!
Thanks....
