### ISSUE TITLE
Can't grab cookies :'(

### ISSUE THREAD

**Issue by komarzycho** [fedorovvl/tso_client#311]
For some reason when I'm trying to load in there is an error "can't grab cookies :'(", I've quessed already that's about cookies but what i don't know it's what i should do to resolve the issue,any ideas?

**Comment by fedorovvl** [comment]
no active maintenance?

**Comment by skelgaard** [comment]
Day: Wednesday, October 4th
Game Worlds: (1 - 3) Closed
Start: Approx. 09:00 CEST
End:  Approx. 17:00 CEST

**Comment by komarzycho** [comment]
oh okey thanks for info,I've been looking for any information about maintenance but i found nothing
