### ISSUE TITLE
Problem with the Launcher

### ISSUE THREAD

**Issue by komarzycho** [fedorovvl/tso_client#312]
![tso](https://github.com/fedorovvl/tso_client/assets/38581891/3ec4fa00-df92-434a-ad3f-021140409443)

I've tried to open launcher from many pcs and from many internets and there is still a problem,I've checked the status of polish server and Europe English server,both are active and no one reported anything,but for me the launcher doesn't load idk why tho. I upload image above. Can someone explain to my what's going on with the launcher?

**Comment by wizofaus** [comment]
Thanks, this works.  But why is that different to the latest client.exe that's under releases?

**Comment by fedorovvl** [comment]
fixed i suppose =))
