### ISSUE TITLE
Windows are opening very slow

### ISSUE THREAD

**Issue by ZleFox** [fedorovvl/tso_client#314]
On the new version v 1.5.6.4 opening client windows is very tedious to the point that renders the client unusable. I suspect it is this new experimental multiwindow feature. The window opens for at least 10 seconds and everything is freezed during that time. 
Had to revert to the unofficial release from yesterday

**Comment by fedorovvl** [comment]
no difference between release and previous test builds.. client files are same
latest changes affects only swf, but swf same for test builds and release version
i can't confirm freezes on release version.. all ok for me
need more info

**Comment by ZleFox** [comment]
hmm, very strange. I have updated it again - exactly the same way and it crashed the first time I opened Charming deposits and since then is running fine. I have downgraded it again to check if there is difference. There is none. It is working fine now - no crashes or slow-downs. Seems to be a fluke from yesterday. It is strange because yesterday it way fixed by downgrading - it was not some windows load. 

BTW now I noticed a bug with opening windows with hotkeys. After 3-10 times hotkey invocation of the same tool, the windows stop opening at all(not just the one you are invoking, but most of the other too)  and you have to restart the client. It is the same on the previous version (the not tagged zip). Just right now before submitting it bugged on the second invocation of F4 shortcut
