### ISSUE TITLE
file error

### ISSUE THREAD

**Issue by stels724** [fedorovvl/tso_client#317]
the client refuses to enter the game. I can't fix it. I ask for help .
![Снимок экрана 2023-10-08 125845](https://github.com/fedorovvl/tso_client/assets/147314106/823b3e9e-8f05-4369-89ca-aaa35710024b)

**Comment by fedorovvl** [comment]
pls check availability of https://ubistatic-a.akamaihd.net/
any highlight tools used? remove it all
check hosts file

**Comment by stels724** [comment]
""> Пожалуйста, проверьте наличие [https://ubistatic-a.akamaihd.net/,](https://ubistatic-a.akamaihd.net/) какие-либо инструменты выделения использовались? удали все это проверь файл хостс""

- по ссылке не получается хаъодить. пишет нет доступа к файлу.
хостс проверил ничего не нашел 
![image](https://github.com/fedorovvl/tso_client/assets/147314106/f36ee7a1-5612-4994-a5f4-a35ecf6da7aa)
 дополнительные инструменты выделения не использовались вроде как.
