### ISSUE TITLE
Suggestion: filter in explores/geoligist, default loaded template and template manager

### ISSUE THREAD

**Issue by skelgaard** [fedorovvl/tso_client#32]
a quick filter, where i can put in like "humble" and then only set the type for, for my humbles

also a default loaded template would be a good idea.

in the templates a template edit function where it could set a default type, then a filter again like humble and set it to medium and so on, so if this template is opened and i have gotten a new explorer, it will set it to default setting (prolonged) and will send it out with correct.

**Comment by fedorovvl** [comment]
filter implemented in https://github.com/fedorovvl/tso_client/commit/f7827a782691d4998b6bc82ddba9e604032cbbcf
