### ISSUE TITLE
[Req] Hotkey to open StarMenu

### ISSUE THREAD

**Issue by GregSam** [fedorovvl/tso_client#322]
Hi Team,
could you add a hotkey to open/close StarMenu please.
Ive tested this function call, works fine :)

`globalFlash.gui.ToggleStarMenu(null);`

I have bounded this to the space key, it is more convenient for me to hit space than move and click mouse button.
I think more players would find it useful.

cheers
JZ

**Comment by fedorovvl** [comment]
hi. 
u can create simple userscript like
```
addToolsMenuItem("Toggle StarMenu", ToggleStarMenuHandler);
function ToggleStarMenuHandler(event)
{
	globalFlash.gui.ToggleStarMenu(null);
}
```
![изображение](https://github.com/fedorovvl/tso_client/assets/31754742/359493d2-7589-4b35-bac9-3754a41bafc5)
and then assing hotkey to it in hotkey manager
![изображение](https://github.com/fedorovvl/tso_client/assets/31754742/cf98e614-248a-4bef-b965-0cfa532b9da8)

**Comment by GregSam** [comment]
thanks,
Ill do that.

**Comment by GregSam** [comment]
closed
