### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by fredpenin** [fedorovvl/tso_client#323]
Hey, 
I'm trying to install & lauch the latest version of the client but get this error : 
![client_tHSrxu30nH](https://github.com/fedorovvl/tso_client/assets/43536231/ebad559c-b474-40de-b307-c42f86f629be)

Any solution ? Thank you !

**Comment by fedorovvl** [comment]
hi. active maintenance?

**Comment by fredpenin** [comment]
I can log in through the Web interface, what do you mean ?

**Comment by fedorovvl** [comment]
which region?

**Comment by fredpenin** [comment]
From France

**Comment by fedorovvl** [comment]
which region u choose in client? france?

**Comment by fredpenin** [comment]
Solved it, i was on european english, I hadn't seen France because i tried to scroll down, i supposed the menu to show the upper top. Thank you !
