### ISSUE TITLE
Фильтр быстрого поиска спецов работает кривовато

### ISSUE THREAD

**Issue by BasilMas** [fedorovvl/tso_client#330]
Если ошибиться в фильтре, например. написать "тро" вместо "тру"
![image](https://github.com/fedorovvl/tso_client/assets/76757249/f51932bc-75e4-486d-ad54-b27cd4cdd582) 
а потом поправиться 
![image](https://github.com/fedorovvl/tso_client/assets/76757249/82d9657e-bc89-4322-ba63-43af1f3fbe85)
то фильтр не сработает.
Нужно все удалить
![image](https://github.com/fedorovvl/tso_client/assets/76757249/c733b9f7-af70-4dc8-99fe-a616fc58d5b0)
и больше не ошибаться
![image](https://github.com/fedorovvl/tso_client/assets/76757249/e0b749df-d322-46f8-af47-aef73cfc26bf)

**Comment by fedorovvl** [comment]
fixed in https://github.com/fedorovvl/tso_client/commit/bc4e0448b410cc76fc0af951cafc95bf0685df9d

**Comment by BasilMas** [comment]
Обнаружилось весьма интересное поведение у фильтра
У меня список вываливается такой
пачка Искренних
пачка каких-то еще, допустим Милых
пачка Скромных

я выбираю фильтр **ск** ожидая выбрать только иСКренних и СКромных
И на экране я вижу этот выбор, выделяю их всех мышкой, сверху до низу, выбираю поиск Средний, убираю фильтр
и что я вижу 
пачке разведов между иСКренними и СКромными тоже назначен поиск средний, то по Шифт + ЛКМ выбрались все разведы, даже те, которых не видно на экране
