### ISSUE TITLE
Сортировка/группировка ген при импорте

### ISSUE THREAD

**Issue by BasilMas** [fedorovvl/tso_client#332]
Можно ли как-то реализовать сортировку/группировку ген при импорте по типу гены?
В некоторых шаблонах генералов море, поэтому сложно туда-сюда листать, чтобы посмотреть, кого уже назначил.
Например, вот первый стойкий на 1м экране
![image](https://github.com/fedorovvl/tso_client/assets/76757249/09778f6d-90fc-4434-a55d-0ad20948a76b)
а два других на последнем
![image](https://github.com/fedorovvl/tso_client/assets/76757249/3591efc3-8873-4891-9509-5900849f0ca0)

Если бы они все кучно вывелись  один за одним, было бы удобнее. 
И чтобы два раза не вставать, если бы при сбросе скилов уже назначенные генки не скидывались, было бы ваще супербест. А то назначил десяток, а 11й прокачан иначе, и давай крути шарманку сначала.
Спасибо

**Comment by fedorovvl** [comment]
implemented
