### ISSUE TITLE
Скроллинг звёздного меню в latest build

### ISSUE THREAD

**Issue by h31p** [fedorovvl/tso_client#333]
Использую latest build т.к. установлена Win7, релизный клиент работать отказался, апгрейд системы пока невозможен.

Иногда обновляю его с гитхаба, и с какого-то момента вылез такой глюк: нажатие стрелочек прокрутки в звёздном меню (именно треугольных стрелочек над и под скроллбаром) стало вызывать прокручивание сразу двух строк, а не одной как было раньше. Возврат на предыдущую скачанную версию возвращает нормальное поведение, т.е. это зашито именно в клиенте, а не в игре. А можно вернуть как было, или, если такое поведение и задумано - сделать его конфигуруемым?

Последний скачаный latest build который вёл себя нормально имеет дату 05.10.23, первый скачаный который прокручивает сразу по две - 13.12.23, затронувшее изменение произошло где-то между ними.

Спасибо!

**Comment by BasilMas** [comment]
у меня во всех версиях, релиз и тестовые билды скроллит сразу на 2 строки и довольно давно, и звезду и эксель. Я хз с чем связана проблема, но она похоже выборочная. У меня вин10 (х64)

**Comment by h31p** [comment]
как я упомянул, когда возвращаю билд от 05.10.23 - скроллит снова по одной, как должно быть. если вам тоже критично - могу, с разрешения автора, поделиться )
опробовал эти же оба билда на другом компе, вин10х64 - повторяемость полная, старый по одной, последний по две.
пока катаюсь на старом, но ведь придёт тот момент, когда из-за изменений в игре он перестанет работать..

**Comment by BasilMas** [comment]
да я сам могу скачать, интересно - счас проверю

**Comment by BasilMas** [comment]
Сборки ниже листают по 2 строки звезда/сундук/эксельсиор
![image](https://github.com/fedorovvl/tso_client/assets/76757249/f29cdd6d-151b-4bae-bdf4-789d8c740a0a)
![image](https://github.com/fedorovvl/tso_client/assets/76757249/8da5dad7-312d-489a-9b16-eee1bb11bfc0)

Релиз по одной

![image](https://github.com/fedorovvl/tso_client/assets/76757249/eebbeb73-163d-45db-a924-8fada3eac842)

**Comment by BasilMas** [comment]
> как я упомянул, когда возвращаю билд от 05.10.23 - скроллит снова по одной, как должно быть. если вам тоже критично - могу, с разрешения автора, поделиться ) опробовал эти же оба билда на другом компе, вин10х64 - повторяемость полная, старый по одной, последний по две. пока катаюсь на старом, но ведь придёт тот момент, когда из-за изменений в игре он перестанет работать..

5го у нас был релиз, первая тестовая сборка после релиза уже имеет этот косяк -- @[fedorovvl] pushed 
[ 94f7b70] 
https://github.com/fedorovvl/tso_client/actions/runs/6574820290

**Comment by h31p** [comment]
в эксельсиоре кстати тоже кол-во кристаллов мотается по 2..

**Comment by fedorovvl** [comment]
вроде починил.. надо проверить на последней сборке

**Comment by h31p** [comment]
да, в последнем билде работает как надо, спасибо!
