### ISSUE TITLE
Fairytale castle

### ISSUE THREAD

**Issue by Juup3l1** [fedorovvl/tso_client#334]
If u build  fairytale castle it will start beanstalks inmedietly and u cant stop productions, because it will start producing level 5 < client version says like that. So if u wanna stop fairytale castle production u must login your account, start game with web browser and go fairytale castle and stop the productions.

**Comment by fedorovvl** [comment]
its a bug in game_settings.xml..
Fairytale castle has minProductionLevel="5" in config but works from level 1
why unity not using config parameters - i dont know
`<Building name="WhiteCastle" hitPoints="1000" constructionDuration="600" InstantBuildCosts="10" tradable="false" maxBuildingLimit="1" movable="true" minProductionLevel="5">`
