### ISSUE TITLE
Относительный путь к файлам шаблонов в Закладках  

### ISSUE THREAD

**Issue by BasilMas** [fedorovvl/tso_client#337]
Все же осмелюсь попросить, вдруг случится новогоднее чудо.
Сейчас в файле settings.json путь к файлам шаблонов хранится в абсолютном виде. Для тех, куто играет из двух мест (дом/работа)  это требует необходимости иметь одинаковые пути к папкам. Когда ты сам себе админ на рабочем компе это не проблема, дада, я знаю, что на работе надо работу работать, а не вот это вот все, но все же. Хотелось бы иметь возможность задавать в Настройках часть пути, а остальное уже достраивать.
Вот, например, как выглядят закладки для Юного
![image](https://github.com/fedorovvl/tso_client/assets/76757249/228f8afe-5b25-437a-bbfe-0e976c0673d8)
 
 Выделенную часть можно было бы хранить в виде задаваемой переменной, как это уже сделано для шаблонов
 
![image](https://github.com/fedorovvl/tso_client/assets/76757249/23fabd78-8cb2-4500-a5a7-cef4866cf1a4)

Если путь (или часть пути) не существует, то выдавать ошибку "not exist", аналогично как это работает если удалить физически файл с шаблоном, но оставить его в закладках.
![image](https://github.com/fedorovvl/tso_client/assets/76757249/ee64fd5c-3bdf-4529-b421-1889e5e27334)

С наступающими!

**Comment by fedorovvl** [comment]
implemented in https://github.com/fedorovvl/tso_client/commit/8df1da576c71500b1b37bad162b06a7032bf636f
