### ISSUE TITLE
Active friends - duplicated from the guild

### ISSUE THREAD

**Issue by michalkortas** [fedorovvl/tso_client#350]
Hi, after filtering active friends, duplicated friends are visible if they are both part of our friends list and belong to our guild.

![image](https://github.com/fedorovvl/tso_client/assets/1836004/182de844-5ca8-4cde-a8d4-3924ba78071b)

**Comment by fedorovvl** [comment]
pls check with new swf

**Comment by michalkortas** [comment]
Thx. 

BTW - great job!
