### ISSUE TITLE
Ошибка кеша в мультиоконном режиме 

### ISSUE THREAD

**Issue by BasilMas** [fedorovvl/tso_client#358]
В последней тестовой сборке есть проблема с открытием прикла в новом окне при включенной мультиоконности
![image](https://github.com/fedorovvl/tso_client/assets/76757249/80a87e82-cbef-4456-be66-306fb5463261)

В предыдущей и двух более ранних сборках такой проблемы нет
![image](https://github.com/fedorovvl/tso_client/assets/76757249/ee03f54d-304a-42c7-a201-e816862abcfd)

**Comment by fedorovvl** [comment]
надо проверить

**Comment by BasilMas** [comment]
пока нет (
![image](https://github.com/fedorovvl/tso_client/assets/76757249/e67cdcf5-4ae4-434f-b5db-896ee9d4e73a)

**Comment by fedorovvl** [comment]
у меня норм заработало после фикса.. 
может проверишь сильней?)

**Comment by BasilMas** [comment]
я  хз куда сильнее( 3 разных акка - одна и  та же ошибка

**Comment by BasilMas** [comment]
Вроде все ОК! Спасибо!
