### ISSUE TITLE
2024-04-17 maintenance in france

### ISSUE THREAD

**Issue by Tartapuce** [fedorovvl/tso_client#359]
Good morning,
Today, between 9:00 a.m. and 12:00 p.m., the French servers underwent an update.
The game was put back online at 11:30 a.m.
No update of the "client.swf" file has been deployed and the client can therefore no longer connect to the French servers...
Question: Is the update planned for today or postponed to tomorrow with the other servers (I presume!)
In any case, thanks for the amazing work on the game client...

;-)))

**Comment by Cdrwbw** [comment]
The swf is on discord settlers fan

**Comment by Tartapuce** [comment]
Sorry, impossible to connect, i have no account on discord......
The auto update function on the client is down ???

**Comment by Tartapuce** [comment]
OK, thanks, the auto-update is on, i'm downloading the new file....
Issue can be close now....

**Comment by BasilMas** [comment]
> OK, thanks, the auto-update is on, i'm downloading the new file.... Issue can be close now....

No full auto-update function/

Sirris or I need to update client.swf manually, after that we upload swf here on GitHub, and then client can download it to player PC.
