### ISSUE TITLE
New update - cannot comnnect with client.

### ISSUE THREAD

**Issue by Coffeeye** [fedorovvl/tso_client#360]
Hey, 

Todays release deny my client from connection.

![image](https://github.com/fedorovvl/tso_client/assets/83951742/404c9b39-a6f3-49df-9cdf-89637499f410)

**Comment by skelgaard** [comment]
update is incomming... its in the discord and soon out too

**Comment by Coffeeye** [comment]
Alright :-) that memo could be assign to the wiki right under the link to swf.
