### ISSUE TITLE
2FA support

### ISSUE THREAD

**Issue by denser** [fedorovvl/tso_client#364]
Need to support two factor auth.

**Comment by skelgaard** [comment]
not possible... 2fa is for ubisoft only, unofficial client can't support this... turn it of or use the webclient

**Comment by fedorovvl** [comment]
im waiting for PR =)

**Comment by denser** [comment]
got it

**Comment by skelgaard** [comment]
ui.com has nothing todo with TSO ?

**Comment by BasilMas** [comment]
available in last build now
https://nightly.link/fedorovvl/tso_client/workflows/msbuild/master/client.zip

**Comment by SasSam** [comment]
> ![image](https://private-user-images.githubusercontent.com/3440014/339031452-dc497a58-6d5a-400e-a26c-c33f0a47fe02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjM2MTQsIm5iZiI6MTcyMTkyMzMxNCwicGF0aCI6Ii8zNDQwMDE0LzMzOTAzMTQ1Mi1kYzQ5N2E1OC02ZDVhLTQwMGUtYTI2Yy1jMzNmMGE0N2ZlMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTYwMTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWU0MWE4YjQ3ZTVjYzZjZjFjYWE3ZjIyMzI3YzgzNzdhYTY3YzVjMTljODg1NjY2MzQzYmI3NDVkNGJlNDRhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KXJq4gTcdbT7uHJ-OvsbwldfaNt-5cQvph1UFzR8Y7w) Юбики скоро введут обязательность, что думаете?

@denser Ubiquiti and Ubisoft are 2 completely different companies... 😄 

ui.com: "Ubiquiti manufactures and sells wireless data communication and wired products for enterprises and homes under multiple brand names"

Ubisoft: "video game publisher"

**Comment by KarrokDC** [comment]
This feature needs some documentation, where are we supposed to get the 2FA key from?
When I have 2FA enabled it won't let me log in (obviously) so I can't use the function to extract any 2FA key, and if I remove 2FA, I can log in, I can use the extract 2FA key, but it's not a valid string to put in the config box.

**Comment by fedorovvl** [comment]
https://github.com/fedorovvl/tso_client/wiki/Общая-информация-о-клиенте#настройка-2fa
manual for 2fa
