### ISSUE TITLE
client resolution

### ISSUE THREAD

**Issue by pepita47** [fedorovvl/tso_client#369]
I tried  the tso_client  with the exe
it is working good except the resolution is too hight for me ! how can I make it smaller
I can expand the map but evrything is mini
I cannot change the windows11 resolution everytime I want to play with the client !!
can you help me 
thank you

**Comment by Cdrwbw** [comment]
What screen resolution do you have and what screen size?

**Comment by pepita47** [comment]
thank you for answering
I have 3 screen of 27 inches
resolution is 2560-1440  normal for this screen size
I tried the client on both 3 screens , windows 10 and 11 
the result is the same
how can I  down to 1920 *1200  ONLY for the client
because everything look very small 
is there a solution ? otherwise I will  continue playing on unity
thank you

**Comment by fedorovvl** [comment]
there is no solution, client not scaling, only ingame zoom
