### ISSUE TITLE
боевые усилки в шаблоне после его редактирования

### ISSUE THREAD

**Issue by BasilMas** [fedorovvl/tso_client#373]
Если загрузить шаблон, содержащий усилки, и потом по каким-то причинам захотеть его модифицировать нажав Назад
![image](https://github.com/fedorovvl/tso_client/assets/76757249/efcb910f-53b9-4869-bdfe-f1413bb79250)

то как минимум, если оставить только усилки - кнопка Атака не прожмется
![image](https://github.com/fedorovvl/tso_client/assets/76757249/0caa2c01-b97b-4f25-a055-e71026a67e95)
и если тут же попробовать добавить новый усилок - тоже не прожмется

Как оно будет работать, если оставить/добавить атаку генералом - не проверял.

**Comment by BasilMas** [comment]
Если при редактировании оставить или добавить атаку генералом, то генерал в бой уйдет, а усилок не кинется.
![image](https://github.com/fedorovvl/tso_client/assets/76757249/e295aeb3-a0cd-4d5e-a9f1-f95b472422a9)

**Comment by fedorovvl** [comment]
можно проверять

**Comment by BasilMas** [comment]
Спасибо, пофиксено
