### ISSUE TITLE
Системный чат в МО режиме

### ISSUE THREAD

**Issue by BasilMas** [fedorovvl/tso_client#374]
Если получится отображать хотя бы системный чат в МО режиме - будет супер!
а то получается, что часть классных фич (нотификации, лог атаки с таймингами) в этом режиме недоступен :(
Спасибо!

**Comment by fedorovvl** [comment]
можно тестить.. переключатель в настройках

**Comment by BasilMas** [comment]
Супер, завтра - сегодня я в дороге :(

**Comment by BasilMas** [comment]
Работает, спасибо :)
