### ISSUE TITLE
Feature Request - Default setting for in game message multiple collect to choose either star or store.

### ISSUE THREAD

**Issue by kistelek2** [fedorovvl/tso_client#375]
When collecting multiple messages, game defaults to put them into star. Would like to be able to set this in UI setting to store or star as the default.

**Comment by fedorovvl** [comment]
implemented in https://github.com/fedorovvl/tso_client/commit/a5a9a82877bc07758a51767c47c1e453cfdd7831

**Comment by kistelek2** [comment]
Thankyou very much.

**Comment by BasilMas** [comment]
Сломалось после техов
