### ISSUE TITLE
Unable to log in 

### ISSUE THREAD

**Issue by Fergielicious** [fedorovvl/tso_client#376]
unable to log into game keep having the authentification uplay timed out error message :(

**Comment by fedorovvl** [comment]
u have issue only in client? unity works fine?

**Comment by Fergielicious** [comment]
Cant load the website too
________________________________

**Comment by fedorovvl** [comment]
and u open issue here.. why? =))

**Comment by Fergielicious** [comment]
Oops becoz i only try the website when u ask 😋
________________________________

**Comment by fedorovvl** [comment]
u can try --http_timeout 60000 argument

**Comment by Fergielicious** [comment]
Thanks !

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Fergielicious** [comment]
Alls good now ! Thanks for pointing me the right direction 😄
________________________________

**Comment by s0nl4g** [comment]
how use: http_timeout 60000 ? because i have this same problem today

**Comment by skelgaard** [comment]
client.exe --http_timeout 60000

**Comment by s0nl4g** [comment]
but where add it?

**Comment by skelgaard** [comment]
in a command promt or make a shortcut for it with that parameter added

**Comment by s0nl4g** [comment]
![image](https://github.com/fedorovvl/tso_client/assets/115657444/158321d3-0a5f-4a15-bde6-464742178550)

**Comment by skelgaard** [comment]
no idea what it says so can't say anything... does unity work ?

**Comment by s0nl4g** [comment]
nope, this say: Cant connect to server
