### ISSUE TITLE
Сохранение слов триггеров 

### ISSUE THREAD

**Issue by BasilMas** [fedorovvl/tso_client#377]
@Catavasiya
Сиррис, подправь, плиз, когда дойдут руки поле "слова триггеры" в настройках. Сейчас работает некорректно:
1) пользователь ввел "а,б,в" (без пробелов) -> в сеттингс записались "а", "б", "в" без пробелов внутри кавычек
2) пользователь опять открыл настройки (за любой надобностью, про другое поле например) и в поле "тригеры" видит уже "а, б, в" (с пробелами). после сохранения настроек (которое может про другое совсем было) - в сеттигс уже "а", " б", " в", т.е. интерфейсные пробелы записались в настройки.

**Comment by fedorovvl** [comment]
fixed in https://github.com/fedorovvl/tso_client/commit/952986fdc0b3e71965ae2164b89d84897f30d318
