### ISSUE TITLE
Fix autoscroll in Bookbinder or Adventure Bookbinder when pushing books UP

### ISSUE THREAD

**Issue by bankeris** [fedorovvl/tso_client#392]
When you press "Aditional options" button in any Bookbinder there are few options: "Move to top", "Move to bottom" and "Clear Queue", when I press "Move to top" I have to wait and scroll wents up, so I have to scroll down again till I find next book to push up. While on browser I can move any mount of books to TOP not having auto-scroll up. Saves a lot of time

**Comment by fedorovvl** [comment]
swf logic is very hard to modify.. i dont have source code and cant change most of swf logic, sry
