### ISSUE TITLE
Suggestion: Buff manager with time interval

### ISSUE THREAD

**Issue by wojtek1171** [fedorovvl/tso_client#40]
I have a suggestion which should be pretty simple to add in current implementation.
A button in buff manager which alows user to repeat saved buff cycle automatically in some time interval.
E.g. User has saved buff template. Clicks on the button. Popup shows up with input for time interval (e.g. 125 min) and additionaly input for specfic time when the cycle will start.

**Comment by fedorovvl** [comment]
in my opinion, this is too strong automation, which is tantamount to a cheat

**Comment by wojtek1171** [comment]
I see your POV. Thanks for the quick reply. I think the case can be closed :)
