### ISSUE TITLE
Баг или фича?

### ISSUE THREAD

**Issue by BasilMas** [fedorovvl/tso_client#400]
Если взвести "пробовать быструю авторизацию" и заходить с успешным фастлогином, то при попытках изменить через шестеренку какие-то настройки, например, режим открытия окна, то успешный фастлогин наплюет на эту новую настройку. Подозреваю, что и на другие, хранящиеся в settings.dat тоже.
Другими словами.
Я 1й раз запустал клиента, настроил режим открытия окна на 'minimized' и взвел "пробовать быструю авторизацию", запускаю клиента - все минимайзед как я и хочу, т.к. фастлогина нету, имею две обычных авторизации. 

Потом я передумал, выставил в шестеренке 'maximazed', запускаю, имею успешный фастлогин и ..... тадам.... запуск в режиме минимайзед.

Убираю "пробовать быстрый вход", запускаю, снова имею две авторизации и .... тадам.... окно  на весь экран.

Подозреваю, что со всеми другими настройками, хранящимися в settings.dat (lang, window, clientconfig), та же хрень
 

и чтобы два раза не вставать:

Похоже, что приоритет у параметров запуска (например, client.exe --lang de --window fullscreen) и тыды выше, чем у заданных через шестеренку, это так?

**UPD 30/09/2024**
Совершенно точно такая хрень с --clientconfig NICKNAME
Если сначала юзать дефолтный settings.json и взвести галку "пробовать фастлогин", а потом решить юзать свой ник (или стороннее имя), то ничег оне выйдет - т.к. в  settings.dat уже записано дефолтное.

и если на размер окна можно наплевать, то "пропажа" всех закладок может многих расстроить

**Comment by fedorovvl** [comment]
поправил это поведение в https://github.com/fedorovvl/tso_client/commit/afd3407a984d66557da3d06cb99d4ee007db4158

приоритет у аргументов выше чем у файла настроек
