### ISSUE TITLE
Проблема с отключением звуков

### ISSUE THREAD

**Issue by BasilMas** [fedorovvl/tso_client#402]
Catavasiya — Сегодня, в 16:44
включила звук в стандартном меню клиента (до этого без звука играла), отрубила все звуки в настройках рычажками. пока никто не орет, понаблюдаю.

Catavasiya — Сегодня, в 17:53
звуков не было до перезапуска клиента. после перезапуска некоторые звуки вернулись при том, что в настройках по-прежнему все рычажки выключены. в json один почему-то true, но помимо него и другие звуки (которые false) есть. что-то неладное с записью/чтением настроек в/из json.

![image](https://github.com/user-attachments/assets/c84e2237-e900-44af-9667-dce73f45bedd)

вкл/выкл одного рычажка и сохранить привели к тому, что они теперь все включены (и в интерфейсе, и в json)

**Comment by fedorovvl** [comment]
в дебаг окне не спамит при этом строкой "wait some" ?

**Comment by Catavasiya** [comment]
Закрывайте, это я облажалась
