### ISSUE TITLE
Grout Tributes not showing production activity

### ISSUE THREAD

**Issue by rsutherlandii** [fedorovvl/tso_client#405]
In the unity web client, grout tributes are showing production values in the Economy Overview (see screenshot_4_unity). In the portable client, they show zero ("0") (see screenshot_1).
![Screenshot_1](https://github.com/user-attachments/assets/9436b4f2-2304-4f7c-bbfe-602589c3367a)
![Screenshot_4_unity](https://github.com/user-attachments/assets/18cb2107-9fd6-46fa-8af0-eef4567ebdcf)
all tributes are on; I've moved one, to no effect. I've removed the buff, to no effect. I placed the one from the event, with no effect. 

Thanks!
Richie

**Comment by fedorovvl** [comment]
i cant change client logic..
