### ISSUE TITLE
Мультипликатор для стрел в "Типичной войне"

### ISSUE THREAD

**Issue by Urvdmih** [fedorovvl/tso_client#409]
Предлагаю сделать чтобы вместо 
![client_2024-11-07_13-04_774](https://github.com/user-attachments/assets/b8a5769b-831e-4be1-a218-bf208af3e8cf)
было так
![client_2024-11-07_13-04_774_](https://github.com/user-attachments/assets/12d4a873-1f93-4ca7-bfcd-e5330a3b7446)
Т.е. добавить настройку с количеством стрел.

**Comment by skelgaard** [comment]
that would be bad, as its different camps you are attacking and the order of attack can be relevant

**Comment by Urvdmih** [comment]
> that would be bad, as its different camps you are attacking and the order of attack can be relevant

Причем тут порядок атаки, он же не меняется. У вас есть лагерь, на который надо кинуть 5 стрел одинаковых. Причем тут порядок атак вообще? Да и лагеря стрелами сносятся обычно в начале приключения или перед атакой на лагерь.

**Comment by fedorovvl** [comment]
слишком много логики переделывать.. не вижу смысла
