### ISSUE TITLE
New Event

### ISSUE THREAD

**Issue by sroca-81** [fedorovvl/tso_client#413]
New Guild Event causes crash and/or performance issue.
Can't use new functionality

**Comment by Cdrwbw** [comment]
Don't use client to play the event. Don(t validate quest or message of coop aventure vith client, return on unity

**Comment by michalkortas** [comment]
Will it be possible to play on the client during this event in the future? Future editions are planned 2-4 times a year.

**Comment by BasilMas** [comment]
Sirris wrote early - he has no plans to implement this event to client

**Comment by fedorovvl** [comment]
GF will not be implemented, sry
