### ISSUE TITLE
Opening "Market", the forms is empty

### ISSUE THREAD

**Issue by RedzIta** [fedorovvl/tso_client#415]
With the last client's version; when you open the menu item "Market" , the form is empty.
You can see in the image attached.

![The Merchant](https://github.com/user-attachments/assets/43935487-3f1c-4b3b-88ba-dfb4e42a8053)

**Comment by jodurpar** [comment]
Also, if you visit the market, it breaks the client.

**Comment by fedorovvl** [comment]
BB broke something.. wait till next update
![изображение](https://github.com/user-attachments/assets/282cc20d-0c8b-4ca5-b48b-de874aba4d43)

**Comment by fedorovvl** [comment]
BB fixed this bug in 1720-Release_heart
