### ISSUE TITLE
Error a the startup

### ISSUE THREAD

**Issue by zebecasse** [fedorovvl/tso_client#416]
First, sorry about that, but i fight since one week with this issue, i think it's on old one, but impossible to start the client :(

I have the error : "File loading failed! Please check your network connection, clean your browser cache or try again later."

I play on the french server

Somebody have an idea how to fix that please ?

**Comment by skelgaard** [comment]
make sure you don't have -skip in your shortcut to the client.exe.. else try and copy the client.exe to a new folder and run it from there... or even delete the tso_portable folder and reset the client settings by that.... note this will also remove any shortcuts loaded....

**Comment by zebecasse** [comment]
Yes, i change the folders of the client exec, and everything works fine, great thanks !!

**Comment by BradleyJoe** [comment]
> Yes, i change the folders of the client exec, and everything works fine, great thanks !!

For me dosn't work. Last release. (((
