### ISSUE TITLE
wont update 

### ISSUE THREAD

**Issue by WaZZo2010** [fedorovvl/tso_client#42]
hi i downloaded the new client from your page when i was directed to it 

it wont update i try opened it and it says out dated 

plz help i again tried a fresh download client.exe but still no good

**Comment by MkFera** [comment]
the start with client button doesn work anymore.
get an error on line : var tso = (/thisProgram: "(.*)"/g.exec(body))[1];
![2022-09-28_16h01_17](https://user-images.githubusercontent.com/114618057/192877521-5ffd282b-a3d1-458b-bdbe-55e9a6e240bd.png)

**Comment by ElectricImpossible** [comment]
It seems the auto updater that checks for the swf file hasnt been updated.

I belive the following steps will get the client working again.

1. Delete / rename your %localappdata%\temp\tso_portable\ directory
2. Launch the client.exe you used yesterday / before the 28th Sept update. It will load and then complain about the cache being and issue. Close the window.
3. Download the currently client.swf
   https://azurpc.wixsite.com/azurpctso/forum-1/settlers/azurpc-tso-toolbox-1 has a file link to an update swf.

[Location of SWF file](https://i.imgur.com/xJw7XxB.png)

4. You then need to create a shortcut to Fedorovvl's client.exe skipping the update. For example - if your client.exe is in c:\tso use

`"C:\tso\client.exe" --skip`

5. copy the client.swf you downloaded to the following location on your PC, overwrite the current file.

`%localappdata%\temp\tso_portable\`
6. Now launch the game from the shortcut you made in step 4. You should not get an error related to the cache.

**Comment by WaZZo2010** [comment]
seems to be a swf update not completed yet i will wait for it 
bless you all thank you so much

**Comment by BasilMas** [comment]
swf update completed but we haven't new client.swf for update. that's why we have to do it manually
We need to wait for Sirris to make an update of client.swf

**Comment by MkFera** [comment]
copying the file manually  with --skip the portable version works fine :). the other version, that starts from browser, break on script error, something changed in the page ?

**Comment by BasilMas** [comment]
We have No Sirris here at the moment. He is away from PC now.  Be patient. He will probably fix all problems when he comes back.

**Comment by WaZZo2010** [comment]
bless u all so help full

**Comment by fedorovvl** [comment]
main swf fixed
