### ISSUE TITLE
Windows Defender found Trojan:Win32/Bearfoos.BE!ml

### ISSUE THREAD

**Issue by michelmeeuwissen** [fedorovvl/tso_client#48]
The .exe now (since update of windows defender 29-09-2022) reports a Trojan:Win32/Bearfoos.BE!ml on the exe and will delete the file. Possible a false positive. Maybe some old code libraries are used?

**Comment by azurpc** [comment]
You can see code is on github release and yes false positive

**Comment by fedorovvl** [comment]
false positive
