### ISSUE TITLE
TimeOut too low

### ISSUE THREAD

**Issue by MkFera** [fedorovvl/tso_client#52]
I get many login error.
probably our server or my internet connection. 
I noticed that the timeout is only 10 seconds. 
I tried raising it to 30 and in fact after 18 seconds it received the page and everything went well.
I locally changed the code in the postdata function
I put :   request.Timeout = 30000;
It could be useful to put as an argument on the command line for example /TimeOut:30

**Comment by fedorovvl** [comment]
okay, i'll add it in next release

**Comment by MkFera** [comment]
I added the pt-br strings 
{ "pt-br", new Dictionary<string, string>() {
				{ "login", "E-mail" },
				{ "password", "Senha" },
				{ "letsplay", "Jogar" },
				{ "checking", "Verificando o cliente" },
				{ "downloading", "Baixando.." },
				{ "emptypass", "Senha vazia." },
				{ "emptylogin", "E-Mail vazio." },
				{ "collect", "Colecionaveis" },
				{ "collecttip", "Quer usar o marcador de colecionaveis?\nApertar \"yes\" somente apos ativar o UbiCollect.exe!" },
				{ "tryauth", "Tentativa de login #" },
				{ "nomoretry", "ja foi.. cansei :)" },
				{ "auth", "Autenticando" },
				{ "authok", "Autenticado com sucesso " },
				{ "getplay", "Pedindo pagina inicial" },
				{ "cookieerr", "Não consigo achar os cookies :'(" },
				{ "paramserr", "Erro ao obter os parametros" },
				{ "autherr", "Erro de autenticação. resposta - " },
				{ "loginerr", "E-mail ou senha errada." },
				{ "captchaerr", "Recebí o Captha.. tenta mais tarde." },
				{ "uplayerr", "UPLAY não responde." },
				{ "authex", "Exceção na pagina de autenticação." },
				{ "emptyauth", "Resposta vazia .. isso é estranho " },
				{ "getparams", "Obtendo parametros." },
				{ "tsourlerr", "Erro ao obter o parâmetro tsoUrl." },
				{ "nick", "Apelido - " },
				{ "launch", "Iniciar cliente..." },
				{ "run", "JOGAR" },
				{ "exit", "sair" },
				{ "remember", "Lembrar" },
			 }
			}

**Comment by fedorovvl** [comment]
added --http_timeout argument (in ms)
