### ISSUE TITLE
Multiselection for specialists send

### ISSUE THREAD

**Issue by Anprivate** [fedorovvl/tso_client#6]
Is it possible to do multiple specialists selection and select same action for selected group?
Sorry, I can't write in TSO forum and don't know why
PS: здесь по русски писать можно, а то есть еще несколько идей? :)

**Comment by fedorovvl** [comment]
конечно можно :)

**Comment by Anprivate** [comment]
О, баг, Excelsior выглядит вот так:
https://prnt.sc/uNKAQmXaeXGv

**Comment by fedorovvl** [comment]
про мультивыбор идея норм.. получилось как то так
![GIF 05 07 2022 12-21-31](https://user-images.githubusercontent.com/31754742/177296021-3b465841-d92c-466c-892b-422e9cbcbd1e.gif)
с папками.. air к сожалению не знает какую последнюю открывали, там на выбор не особо много местоположений, я решил что "Мои документы" самое правильное
время исполнения возможно можно получить.. гляну
анимация чайника и так не работала.. теперь еще и черный квадрат, думаю не страшно :)

**Comment by Anprivate** [comment]
О, супер, спасибо. В release пока не выложено?
Надо бы, кстати, Cancel (отмена) на что-то поменять. На idle или no action или еще как-то. Просто Cancel - это именно отмена некоего действия, а в данном случае просто отсутствие действия, немного путает.
А по времени исполнения - это было бы очень здорово. Здесь есть вообще голубая мечта, связанная с treasure search во время event'ов - то есть если бы можно было задать минимальное/максимальное время поиска и для всех свободных эксплореров режим поиска выбирался бы автоматически в этих пределах. Для чего это нужно - для того, чтобы:
а) эксплореры успели вернуться до того, как я лягу спать.
б) эксплореры вернулись после того, как я проснусь
То есть сейчас сидишь и высчитываешь в голове - так, лягу спать примерно в 23, значит осталось 4 часа, ага, вот этих можно послать на средний поиск, а этих на короткий. А эти вообще не успеют вернуться, значит я буду за компом в 11, значит надо их слать на prolonged. Вот бы это автоматизировать... Но это уже в категории мечт :)
По поводу сохранений - может просто сохранять в папку, где лежит сам клиент?
И еще - там режим open/save чуть разный - для open выбрана маска "*.txt", а для save "*.*". Поэтому при сохранении при  наборе имени файла очень легко убить дефолтное расширение txt и потом в open этот файл уже не увидится.

**Comment by fedorovvl** [comment]
в общем время я добавил и почти сразу убрал.. очень дорогая по времени операция расчета времени для каждого таска для каждого спеца.. мои пара десятков спецов и те стали грузиться секунд 30
мультивыбор релизнул

**Comment by Anprivate** [comment]
А нельзя это время куда-нибудь закешировать? То есть один раз рассчитать  и дальше брать из кеша.
По поводу cancel и места сохранения - понял, некритично.

**Comment by Anprivate** [comment]
Букинг и ребукинг всё-таки крайне редкая вещь. Можно сделать отдельный пункт в меню - recalculate times after rebooking. А с кнопкой не сильно удобно - нужно сразу видеть время при выборе пункта чтобы понимать, что выбрал правильный. Хотя можно и с кнопкой - перед submit проверить, что нигде не ошибся в выборе.
PS: windows defender стал ругаться на вирус в свежем релизе, раньше такого не было :(

**Comment by fedorovvl** [comment]
я немного изменил разметку основного окна.. может какая то хеш сумма поменялась и файл якобы опять "скачан из интернета опасность!!"

**Comment by BasilMas** [comment]
ох вы понаписали! Можно своих 5 копеек? Если это только мне так неудобно - то можно забить, и не делать.
Мне удобнее Save/Load поставить за Submit, т.е. такой поpядок кнопок привычнее
Submit   Save     Load     Cancel

**Comment by fedorovvl** [comment]
всем не угодишь.. для меня кнопки темплейта это отдельная как бы группа.. отправить и отмена другая группа
пихать группу темплейтинга посередине другой группы ну как то не комильфо прям

**Comment by BasilMas** [comment]
Согласен. Но Сабмит мы жмем чаще, а она в середине. Поэтому согласен на другие мнения.  Как вариант
Submit Cancel Save Load 
первая группа Слать/не слать, вторая - работа с пресетами

**Comment by MikeIceman** [comment]
Согласитесь что это вкусовщина. Кому-то так удобно, кому-то эдак.
Кстати, две группы пожно просто разнести влево-вправо. Слева Load/Save, Справа Submit/Cancel
Бутстрап как бы позволяет. И вообще вопросов ни у кого не останется

P.S. Я не UX/UI, я только предложил

**Comment by Urvdmih** [comment]
> в общем время я добавил и почти сразу убрал.. очень дорогая по времени операция расчета времени для каждого таска для каждого спеца.. мои пара десятков спецов и те стали грузиться секунд 30 мультивыбор релизнул

Можно ли добавить чекбоксы слева? А то я подозреваю не всем очевидно, что можно выделять строчки через контрол и шифт. По поводу спецов, я думаю можно сделать жестко заданные колонки без расчетов, с указанным временем непрокачанного спеца, прокачанного на поиск сокровищ (можно даже дать ссылку на тех же дворян), и прокачанные+ПУД. Тогда тормозить не будет, а кто прокачался не по стандарту - тот ССЗБ.

**Comment by fedorovvl** [comment]
чекбоксы точно лишние.. проще ридми написать где указать на возможность выбора мышкой
если добавить столько колонок то модальное окно просто не влезет в основное окно и будет кривота

**Comment by fedorovvl** [comment]
добавил шифт + клик
сдвинул кнопки шаблонов влево

**Comment by BasilMas** [comment]
> И еще - там режим open/save чуть разный - для open выбрана маска "_.txt", а для save "_.*". Поэтому при сохранении при наборе имени файла очень легко убить дефолтное расширение txt и потом в open этот файл уже не увидится.

Вот это бы да, еще при случае поправить

**Comment by Urvdmih** [comment]
> чекбоксы точно лишние.. проще ридми написать где указать на возможность выбора мышкой если добавить столько колонок то модальное окно просто не влезет в основное окно и будет кривота

Там же дофига места. Числа же мало места занимают, плюс можно сократить различные отступы и сдвинуть вправо колонку где выбор типа поиска.
<img width="674" alt="eV6x33M6Eg" src="https://user-images.githubusercontent.com/9265883/178140836-cbda058a-76c3-4b83-89a3-241c1af24830.png">
.

**Comment by BasilMas** [comment]
> > чекбоксы точно лишние.. проще ридми написать где указать на возможность выбора мышкой если добавить столько колонок то модальное окно просто не влезет в основное окно и будет кривота
> 
> Там же дофига места. Числа же мало места занимают, плюс можно сократить различные отступы и сдвинуть вправо колонку где выбор типа поиска. <img alt="eV6x33M6Eg" width="674" src="https://user-images.githubusercontent.com/9265883/178140836-cbda058a-76c3-4b83-89a3-241c1af24830.png"> .

дофига места у тех, кто использует дефолтные имена pазведов, у меня они почти все пеpеименованы по задачам (бафы, пpиклы, сокpовища) и места мало

**Comment by fedorovvl** [comment]
получилось как то так
![time_column](https://user-images.githubusercontent.com/31754742/178148531-2d3a4b35-5ba8-4284-bdd2-aae8daff91ce.gif)
что будет при сотне другой разведов если честно не знаю :)

**Comment by Anprivate** [comment]
Класс, хочу хочу хочу :)

**Comment by BasilMas** [comment]
я хз как у тебя вышли разночтения, но у меня и по геологам (качаны) и по разведам (качаны), но без ПУДа (конкретно счас он неактивен) посчитало все как и положено при разной прокачке на разных акках

**Comment by BasilMas** [comment]
> Попробовал. Что-то ничего не понял - а как время вычисляется? Ну вот, например. Беру Stone Cold Geologist и хочу послать на Granite. В клиенте мне показывается время 5h36m. А реальное время - 2h14m Thorough и уголь - в клиенте 2h48m, реальное время - 6h43m

я хз как у тебя вышли разночтения, но у меня и по геологам (качаны) и по разведам (качаны), но без ПУДа (конкретно счас он неактивен) посчитало все как и положено при разной прокачке на разных акках

**Comment by Anprivate** [comment]
Ну, то что PFB не учитывается - я уже понял. ОК, проверяю на типичных для меня посылах (PFB активен, то есть надо умножать время на 0.8):
Archeological - gold - 1h24m - 1h07 - корректно
Charming - iron - 42m - 33m36s - корректно
Stone cold - granite - 5h36m - 2h14m - ровно в два раза больше. Видимо, не учтён талант - Find **stone, marble, and granite** deposits of twice the normal size, **in half the normal time**
Thorough - coal - 2h48m - 6h43m - в 3 раза меньше. **He takes three time as long on deposit searches**, but he also find three times bigger deposits
Похоже просто не все "встроенные" таланты учитываются

**Comment by Anprivate** [comment]
Versed - marble - 21m - 8m24s - Finds 50% bigger deposits, **50% faster**

**Comment by fedorovvl** [comment]
залил новый релиз.. проглядел один момент со скилами
теперь точно как в клиенте логика должна быть

**Comment by Anprivate** [comment]
А что за "experimental buff manager (wip)" упоминается в предыдущем релизе? Не нашёл о нём упоминаний
