### ISSUE TITLE
--collect not working ?

### ISSUE THREAD

**Issue by skelgaard** [fedorovvl/tso_client#7]
it seems adding --collect as it says in the PR is not working, looks like the webserver on port 9000 is not started to get the pinky to work

**Comment by fedorovvl** [comment]
you need UbiCollect to use --collect feature. download latest from https://sirris.tsomaps.com/UbiCollect2_2.zip
run ubicollect, then run client, right click on globe icon in tray and click Get update (once on first time and then after every swf update)

**Comment by skelgaard** [comment]
well related to the other issue , if that was the text in English, then we would have a chance to understand that is what is needed... i will try.. thanx :)

**Comment by skelgaard** [comment]
This worked.
Should add this info to the PR readme file, so others have ideas to on getting this to work :) or build them together, so that not need 2 different running though
