### ISSUE TITLE
English text

### ISSUE THREAD

**Issue by skelgaard** [fedorovvl/tso_client#8]
can we please get the text in English (or selectable language) so that we are more that have a chance to understand what it says ;)

**Comment by fedorovvl** [comment]
what are you talking about?
who says?

**Comment by skelgaard** [comment]
all the text are in russian when starting the client

**Comment by BasilMas** [comment]
Use parameters, for ex
`client.exe --lang en` 
starts the client with English interface
`client.exe --lang de` 
with German interface

There are all the language parameters 

`--lang [de|us|en|fr|ru|pl|es2|es|nl|cz|pt|it|el|ro]`

**Comment by skelgaard** [comment]
just tried that, not giving the the messages in english
![billede](https://user-images.githubusercontent.com/13235820/177421175-06ce720a-9c63-442a-a94e-41146964c71d.png)

**Comment by BasilMas** [comment]
Yep :( parameter using changes the game interface only not the client one

**Comment by skelgaard** [comment]
the game interface language is fine....

**Comment by BasilMas** [comment]
> the game interface language is fine....

I will write 'readme' soon with all explanations

**Comment by MikeIceman** [comment]
This is because login background is a static image with russian. Unfortunately it is impossible to change it right now.

**Comment by skelgaard** [comment]
yes i hope that this and the other russian text will be changed to be in a translation file that either follows realm language or has own setting for startup language :)
will also make more ppl trust this... most of my guildies says what is this and why is it not in english when i send them here....

**Comment by fedorovvl** [comment]
> most of my guildies says what is this and why is it not in english when i send them here....

Nothing ventured, nothing gained. haha

**Comment by fedorovvl** [comment]
try last build.. change region to non ru

**Comment by ElectricImpossible** [comment]
> try last build.. change region to non ru

Build [v1.4.6]([https://github.com/fedorovvl/tso_client/tree/v1.4.6 ]) is great!
