### ISSUE TITLE
Current branch Collectibles finder issue

### ISSUE THREAD

**Issue by PiTi2k5** [fedorovvl/tso_client#92]
Hello, with actually branch, the Collectibles finder doesnt work anymore.
Remove script/readd doesnt solve it.
Lang: german
Last release the Collectibles finder works fine.

**Comment by PiTi2k5** [comment]
Yes i build it from master branch, until this https://github.com/fedorovvl/tso_client/tree/0424a466b29ee78dcc2bfde9805bcd87074ed312 commit Collectibles finder works fine

**Comment by PiTi2k5** [comment]
I mean that under tools....

**Comment by PiTi2k5** [comment]
Ok, have double checked the last commits, your last commit "remove old alerts" breaks the Collectibles finder script under tools.

**Comment by fedorovvl** [comment]
oh.. u right )
